version: '3.9'

services:
  optack:
    image: optack
    volumes:
      - ./packages/optack/packages/core/src:/app/src

  storybook:
    image: optack
    volumes:
      - ./packages/optack/packages/core/src:/app/src

  site:
    command: yarn dev
    image: mtfmusicals
    env_file:
      - .env
    volumes:
      - ./packages/jamstack/public:/home/public
      - ./packages/jamstack/src:/home/src

  web_db:
    volumes:
      - sql_data:/var/lib/mysql

  wp:
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', 'development' );

        # Performance
        define( 'COMPRESS_CSS', true );
        define( 'COMPRESS_SCRIPTS', true );
        define( 'CONCATENATE_SCRIPTS', true );
        define( 'ENFORCE_GZIP', true );

        # /* Updates */
        define( 'WP_AUTO_UPDATE_CORE', true );
        define( 'CORE_UPGRADE_SKIP_NEW_BUNDLED', true );

        # /* Debugging */
        define( 'WP_DISABLE_FATAL_ERROR_HANDLER', false );   // 5.2 and later
        define( 'WP_DEBUG', false );
        define( 'WP_DEBUG_LOG', false );
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 'Off' );
        if ( WP_ENVIRONMENT_TYPE !== 'production' ) {
          define( 'SCRIPT_DEBUG', true );
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_LOG', true );
          @ini_set( 'log_errors', 'On' );
          @ini_set( 'error_log', '/home/logs/php_error.log' );
        }

        # / * Security */
        # define( 'FORCE_SSL_ADMIN', true );
        # define( 'WP_HTTP_BLOCK_EXTERNAL', true );
        define( 'GRAPHQL_JWT_AUTH_SECRET_KEY', 'YOUR_STRONG_SECRET' );

    volumes:
      - ./packages/theme/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # Persist wp-content
      - wp_data:/var/www/html/wp-content/plugins
      - wp_data:/var/www/html/wp-content/uploads
      # Load dev docs
      - ./logs:/home/logs
      - ./packages/optack/packages/wp-plugin:/var/www/html/wp-content/plugins/optack
      - ./packages/theme:/var/www/html/wp-content/themes/mtfmusicals
