version: '3.9'

services:
  jamstack:
    image: jamstack
    build:
      context: ./packages/jamstack
      tags:
        - ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${NETWORK}/jamstack:${TAG:-latest}
    restart: on-failure
    expose:
      - '3000'
    networks:
      - public-web

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DB_USER}
    networks:
      - public-web

  cms:
    image: wordpress:latest
    restart: always
    expose:
      - '8080'
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
    depends_on:
      - db
    networks:
      - public-web

networks:
  public-web:
