version: '3.9'

services:
  jamstack:
    build: ./packages/jamstack
    image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/jamstack:${TAG}
    restart: always
    ports:
      - '32768:3000'
    networks:
      - wordpress

  web_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DB_USER}
    networks:
      - wordpress

  wp:
    image: wordpress:latest
    restart: always
    ports:
      - '32769:80'
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
    depends_on:
      - web_db
    networks:
      - wordpress

volumes:
  sql_data:
  wp_data:

networks:
  wordpress:
    driver: bridge
