version: '3.9'

services:
  # optack:
  #   volumes:
  #     - ./packages/optack/packages/core/src:/app/src

  # storybook:
  #   build: ./packages/optack
  #   image: optack
  #   restart: always
  #   command: yarn storybook
  #   ports:
  #     - '32766:6006'
  #   volumes:
  #     - ./packages/optack/packages/core/src:/app/src

  site:
    command: yarn dev
    volumes:
      - ./packages/jamstack/public:/home/public
      - ./packages/jamstack/src:/home/src

  web_db:
    volumes:
      - sql_data:/var/lib/mysql

  wp:
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # Persist wp-content
      - wp_data:/var/www/html/wp-content/plugins
      - wp_data:/var/www/html/wp-content/uploads
      # Load dev docs
      - ./logs:/home/logs
      - ./packages/optack/packages/wp-plugin:/var/www/html/wp-content/plugins/optack
      - ./packages/theme:/var/www/html/wp-content/themes/mtfmusicals
