version: '3.9'

services:
  web_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sql_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - '32769:80'
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', 'development' );

        # Performance
        define( 'COMPRESS_CSS', true );
        define( 'COMPRESS_SCRIPTS', true );
        define( 'CONCATENATE_SCRIPTS', true );
        define( 'ENFORCE_GZIP', true );

        # /* Updates */
        define( 'WP_AUTO_UPDATE_CORE', true );
        define( 'CORE_UPGRADE_SKIP_NEW_BUNDLED', true );

        # /* Debugging */
        define( 'WP_DISABLE_FATAL_ERROR_HANDLER', false );   // 5.2 and later
        define( 'WP_DEBUG', false );
        define( 'WP_DEBUG_LOG', false );
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 'Off' );
        if ( WP_ENVIRONMENT_TYPE !== 'production' ) {
          define( 'SCRIPT_DEBUG', true );
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_LOG', true );
          @ini_set( 'log_errors', 'On' );
          @ini_set( 'error_log', '/home/logs/php_error.log' );
        }

        # / * Security */
        # define( 'FORCE_SSL_ADMIN', true );
        # define( 'WP_HTTP_BLOCK_EXTERNAL', true );
        define( 'GRAPHQL_JWT_AUTH_SECRET_KEY', 'YOUR_STRONG_SECRET' );
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # Persist wp-content
      - wp_data:/var/www/html/wp-content/plugins
      - wp_data:/var/www/html/wp-content/uploads
      # Load dev docs
      - ./logs:/home/logs
      - ./packages/dojo:/var/www/html/wp-content/plugins/dojo
      - ./packages/theme:/var/www/html/wp-content/themes/mtfmusicals
    depends_on:
      - web_db
  # dojo:
  #   build: ./packages/dojo
  #   image: dojo
  #   restart: always
  #   ports:
  #     - '3000'
  #   volumes:
  #     - ./packages/dojo/react/src:/home/dojo/src

volumes:
  sql_data:
  wp_data:
