version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9234:80
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: mtf_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '128M');
        define('WP_DEFAULT_THEME', 'mtf');
        define('MEDIA_TRASH', true);
    volumes:
      - ./dist:/var/www/html/wp-content/themes/mtf
      - ./wp-plugins:/var/www/html/wp-content/plugins

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./wp-data:/var/lib/mysql
