import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Page from '../components/templates/Page';
import chalk from 'chalk';

const Single: NextPage = (props: any) => {
  console.debug(chalk.green(JSON.stringify(props)));

  const [data, loadData] = useState({});
  useEffect(() => {
    // console.debug(chalk.green('foo'));
    (async () => {
      try {
      } catch (error: any) {
        console.error(chalk.red('Error message:', error.message));
      }
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Page />
    </>
  );
};

export const getStaticPaths = async () => {
  try {
    const graphql = `{
      pages(where: {status: PUBLISH}, first: 100) {
        nodes {
          uri,
          id
        }
      }    
    }`;

    const query = graphql.replaceAll(/\s/gi, '');
    const res = await fetch(process.env.API_URL + `/graphql?query=${query}`, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    const json = await res.json();
    const data = json.data;

    if (!data || !data.pages.nodes)
      throw new Error(json.errors.map((error: any) => error.message));

    const nodes = data.pages.nodes.map((node: any) => {
      const slug = node.uri.split('/').filter(Boolean);
      return { params: { slug: slug } };
    });

    return {
      paths: nodes,
      fallback: false,
    };
  } catch (error: any) {
    console.error(chalk.red('Error message:', error.message));
  }
};

export const getStaticProps = async (context: any) => {
  try {
    const graphql = `{
      pageBy(uri: "${context.params.slug.join('/')}") {
        title,
        template {
          templateName
        },
        content    
      }  
    }`;

    const query = graphql.replaceAll(/\s/gi, '');
    const res = await fetch(process.env.API_URL + `/graphql?query=${query}`, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    const json = await res.json();
    const data = json.data;

    if (!data || !data.pageBy)
      throw new Error(json.errors.map((error: any) => error.message));

    return {
      props: data.pageBy,
    };
  } catch (error: any) {
    console.error(chalk.red('Error message:', error.message));
  }
};

export default Single;
