import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/organisms/Header';
import Footer from '../components/organisms/Footer';
import EventsGrid from '../components/organisms/EventsGrid';
import Hero from '../components/organisms/Hero';
import Gallery from '../components/organisms/Gallery';
import NewsGrid from '../components/organisms/NewsGrid';
import Programming from '../components/templates/Programming';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main>
        <Hero />
        <blockquote
          style={{ height: '262px', width: '50%', marginLeft: '40%' }}
        >
          MTF is an accessible and brave creative space where all artists of all
          backgrounds at any stage of their career can be supported throughout
          their process.
        </blockquote>
        <EventsGrid />
        <Gallery />
        <Programming />
        <NewsGrid />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
