import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Events from '../components/Events';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main>
        <Hero />
        <blockquote
          style={{ height: '262px', width: '50%', marginLeft: '40%' }}
        >
          MTF is an accessible and brave creative space where all artists of all
          backgrounds at any stage of their career can be supported throughout
          their process.
        </blockquote>
        <Events />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
